### ISSUE TITLE
disable_secrets option not working

### ISSUE THREAD

**Issue by ShivamKumarDevliyal** [Checkmarx/kics-github-action#121]
When including the disable_secrets argument in the workflow, irrespective of the boolean value being passed it disables secrets scanning.

To Reproduce:
``` yaml
-   name: "Scan with KICS"
    uses: checkmarx/kics-github-action@v1.7.0
    with:
        disable_secrets: false
```
