### ISSUE TITLE
Any option for multiple Path?

### ISSUE THREAD

**Issue by lucasp0r** [Checkmarx/kics-github-action#29]
Can you add any option to multiple path? Or i need add more steps of actions for work to more paths to different types of iac code.

**Comment by joaoReigota1** [comment]
Hello @lucasp0r, sorry for the late response, the multiple option path is available, pass in the path [input](https://github.com/Checkmarx/kics-github-action#inputs) all the paths you want KICS to scan.

Example:

```YAML
# Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # Scan Iac with kics
    - name: run kics Scan
      uses: checkmarx/kics-action@v1.3
      with:
        # scanning two directories: ./terraform/ ./cfn-templates/ plus a single file
        path: 'terraform,cfn-templates,my-other-sub-folder/Dockerfile'    <------
        output_path: 'results.json'
    # Display the results in json format
    - name: display kics results
      run: |
        cat results.json
```
