### ISSUE TITLE
🐛 `Cannot read property 'size' of undefined` Error

### ISSUE THREAD

**Issue by AErmie** [Checkmarx/kics-github-action#44]
When attempting to use the GitHub action, the Action throws an error `Error: Cannot read property 'size' of undefined`, which seems to be an issue with the Action itself (specificially the `index.js` and `task_queues.js` files).

**Sample Action Workflow**

```YAML
- name: Run Checkmarx KICS Scan
  uses: checkmarx/kics-action@v1.3
  with:
    path: ./terraform/azure
    platform_type: terraform
    fail_on: medium,high
    output_formats: sarif
    disable_full_descriptions: false
    disable_secrets: false
    enable_comments: true
    verbose: true
```

**Output Received**
```CMD
Running KICS action...
GET https://api.github.com/repos/checkmarx/kics/releases/latest 200
TypeError: Cannot read property 'size' of undefined
    at getReleaseInfo (/home/runner/work/_actions/checkmarx/kics-action/v1.3/dist/index.js:18004:27)
    at Object.installKICS (/home/runner/work/_actions/checkmarx/kics-action/v1.3/dist/index.js:18018:25)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async main (/home/runner/work/_actions/checkmarx/kics-action/v1.3/dist/index.js:18449:9)
Error: Cannot read property 'size' of undefined
```
