### ISSUE TITLE
Does not show severity in Code Scanning Alerts

### ISSUE THREAD

**Issue by the-tatanka** [Checkmarx/kics-github-action#51]
KICS only shows Error or Nore instead of the severity. The reuslts.json file shows severity ratings.

![image](https://user-images.githubusercontent.com/59142915/164558254-40e5cc04-792d-4e26-9d8f-ab6f6ccfbe17.png)

Would be nice to also see the severity in the Code Scanning Alerts tab.
Example repo: https://github.com/the-tatanka/product-portal-backend

```
name: "KICS"

on:
  push:
    branches: [ main, master ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main, master ]
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
  schedule:
    - cron: '28 15 * * 3'

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
    - uses: actions/checkout@v2

    - name: KICS scan
      uses: checkmarx/kics-github-action@v1.5
      with:
        # Scanning two directories: ./terraform/ ./cfn-templates/ plus a single file
        path: '.'
        # Fail on HIGH and MEDIUM severity results
        fail_on: high,medium
        # when provided with a directory on output_path
        # it will generate the specified reports file named 'results.{extension}'
        # in this example it will generate:
        # - results-dir/results.json
        # - results-dir/results.sarif
        output_path: kicsResults/
        output_formats: 'json,sarif'
        # If you want KICS to ignore the results and return exit status code 0 unless a KICS engine error happens
        # ignore_on_exit: results
        # GITHUB_TOKEN enables this github action to access github API and post comments in a pull request
        token: ${{ secrets.GITHUB_TOKEN }}
        # enable_comments: true

    # Display the results in json format
    - name: Display kics results
      run: |
        cat kicsResults/results.json
      if: always()

    # Upload findings to GitHub Advanced Security Dashboard
    - name: Upload SARIF file for GitHub Advanced Security Dashboard
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: kicsResults/results.sarif
      if: always()
```
