### ISSUE TITLE
Fails when more than one path is specified

### ISSUE THREAD

**Issue by the-tatanka** [Checkmarx/kics-github-action#52]
I want to scan to paths: 
- "."
- "./docker"

It seems that KICS is not auto detecting the Dockerfiles which are not starting with "Dockerfile."
For example it does not find this file: https://github.com/the-tatanka/product-portal-backend/blob/main/docker/Dockerfile-provisioning-service

Example repo: https://github.com/the-tatanka/product-portal-backend

Example config:
```
name: "KICS"

on:
  push:
    branches: [ main, master ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main, master ]
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
  schedule:
    - cron: '28 15 * * 3'

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
    - uses: actions/checkout@v2

    - name: KICS scan
      uses: checkmarx/kics-github-action@v1.5
      with:
        # Scanning two directories: ./terraform/ ./cfn-templates/ plus a single file
        path: './, ./docker/'
        # Fail on HIGH and MEDIUM severity results
        fail_on: high,medium
        # when provided with a directory on output_path
        # it will generate the specified reports file named 'results.{extension}'
        # in this example it will generate:
        # - results-dir/results.json
        # - results-dir/results.sarif
        output_path: kicsResults/
        output_formats: 'json,sarif'
        # If you want KICS to ignore the results and return exit status code 0 unless a KICS engine error happens
        # ignore_on_exit: results
        # GITHUB_TOKEN enables this github action to access github API and post comments in a pull request
        token: ${{ secrets.GITHUB_TOKEN }}
        # enable_comments: true

    # Display the results in json format
    - name: Display kics results
      run: |
        cat kicsResults/results.json
      if: always()

    # Upload findings to GitHub Advanced Security Dashboard
    - name: Upload SARIF file for GitHub Advanced Security Dashboard
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: kicsResults/results.sarif
      if: always()
```

Error message:
```

> kics-github-action@1.0.0 build
> ncc build src/main.js

ncc: Version 0.31.1
ncc: Compiling file index.js into CJS
727kB  dist/index.js
727kB  [3208ms] - ncc 0.31.1
Running KICS action...
Error: ENOENT: no such file or directory, open 'kicsResults/results.json'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at readJSON (/app/dist/index.js:14815:24)
    at main (/app/dist/index.js:14876:31)
    at /app/dist/index.js:14890:1
    at /app/dist/index.js:14892:3
    at Object.<anonymous> (/app/dist/index.js:14895:12)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'kicsResults/results.json'
}
```
