### ISSUE TITLE
enable_comments fails because it cannot open results.json at a provided path

### ISSUE THREAD

**Issue by VladMasarik** [Checkmarx/kics-github-action#62]
When we allow kics github action to create comments on PRs, and set the `results.json` path to anything other than default, the action fails with a message that such file does not exist, but we are able to print the file in the next CI step without an issue.

![image](https://user-images.githubusercontent.com/28529900/191530852-f8c8c201-96fb-4512-abcb-2597ee26b95b.png)

This is the config that we are using.
![image](https://user-images.githubusercontent.com/28529900/191531364-35f7e449-6647-42df-9395-04621c212ab7.png)

**Comment by Apollorion** [comment]
I, too, am having this issue. I have narrowed it down to something being wrong with the, seemingly unrelated, `path` variable.

For some reason, when `enable_comments: true` and the `path` is provided via a github variable (ex `path: ${{matrix.modules}}`) it causes this problem.

It ONLY appears to happen when you use a github variable, if you hardcode whats in the variable it works fine.

`path: "/github/workspace/aws/dev/config.tf,/github/workspace/aws/dev/s3.tf"` works
`path: ${{matrix.modules}}` does not

I've even echo'd out the variable to see the difference and nothing seems to stand out what the issue could be here.
```yaml
      - name: echo what
        run: |
          echo "${{matrix.modules}}"
          echo "/github/workspace/aws/dev/config.tf,/github/workspace/aws/dev/s3.tf"
 ```
 returns:
 ```
 /github/workspace/aws/dev/config.tf,/github/workspace/aws/dev/s3.tf
/github/workspace/aws/dev/config.tf,/github/workspace/aws/dev/s3.tf
```
