### ISSUE TITLE
enable_comments fails posting a comment with 404

### ISSUE THREAD

**Issue by VladMasarik** [Checkmarx/kics-github-action#63]
When `enable_comments` are enabled, the action fails with 404. Not sure if it is the cause, but the URL seems to have double `//`, which would explain it, but I was not able to find a source of the extra `//`
![image](https://user-images.githubusercontent.com/28529900/191533200-2f5c8eb2-03f3-4f13-ab7b-3c626ba0e446.png)

**Comment by zali-fd** [comment]
> When `enable_comments` are enabled, the action fails with 404. Not sure if it is the cause, but the URL seems to have double `//`, which would explain it, but I was not able to find a source of the extra `//` ![image](https://user-images.githubusercontent.com/28529900/191533200-2f5c8eb2-03f3-4f13-ab7b-3c626ba0e446.png)

Do you have the `token `parameter set to `${{secrets.GITHUB_TOKEN}}`?

**Comment by VladMasarik** [comment]
@zali-fd  We use `token: ${{ github.token }}`. This is our config
```
- name: KICS Scan Examples
  uses: checkmarx/kics-github-action@v1.5
  with:
    config_path: ./kics.yaml
    path: ${{matrix.examples}}
    token: ${{ github.token }}
    fail_on: high,medium
```
Which I hope is the same thing https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow

**Comment by jorsmatthys** [comment]
@VladMasarik Was your workflow triggered from a pull request ?  

We saw the same thing when we tried to manually trigger a workflow (workflow_dispatch) with the `enable_comments ` option still active. Normally the URL should look like `.../issues/<number-refereing-to-your-pr>/comments`. If the event that triggered the workflow was not a pr, there is no issue number on the event and you end up with an url like the one in your screenshot.

**Comment by VladMasarik** [comment]
@jorsmatthys Hmm interesting. I checked, and yes it seems that we are using the `on: pull_request` trigger, and nothing else. However, it could still explain my problem, as I just noticed that someone already enabled the comments in our CI pipeline, and it seems to be working just fine. Therefore, I think this issue can be closed, as it resolved itself somehow. Thank you!

**Comment by admiralAwkbar** [comment]
Hello @VladMasarik !

I was looking through the code and wanted to propose some help for users who are running on `push` and not always `pull_request`

you have the following code in `main.js`
```js
try {
        const octokit = github.getOctokit(githubToken);
        let context = {};
        let repo = '';
        let prNumber = '';

        if (github.context) {
            context = github.context;
            if (context.repo) {
                repo = context.repo;
            }
            if (context.payload && context.payload.pull_request) {
                prNumber = context.payload.pull_request.number;
            }
        }
```

Can you add a secondary check to see if we can get the PR id from the commit that came in?

## Possible solution

- Create a second check to see if the payload came from a `push`
- Run a similar command like `gh pr list --search ${{ github.sha }} --json number --jq '.[0].number'`
  - That will return the first `PR_ID` it can find with that commit
 
You can then do a simple check to make sure its a digit, and done :)
If not, it fails as normal with a simple `404` as it couldn't find a `commit sha`

This would be a very nice and low cost improvement...

If my JS was any better i would add the block but i hope this makes sense

thank you for a really cool tool BTW...

**Comment by admiralAwkbar** [comment]
Another maybe more simple would be to be able to pass a with statement to the Action:

```yml
# Run KICS
      - name: Start IaC Scan (KICS Scan)
        uses: checkmarx/kics-github-action@v1.7.0
        with:
          path: ${{ steps.validate-input.outputs.UPDATED_PATH }}
          fail_on: ${{ steps.validate-input.outputs.UPDATED_FAIL_ON }}
          issue_id: ${{ steps.validate-input.outputs.UPDATED_ISSUE_ID }}
```

This would put the work back on the user to give correct info and you would only have to check if that var is passed... Just thinking out loud...
