### ISSUE TITLE
Error finding results when output-name specified

### ISSUE THREAD

**Issue by lewis-shell** [Checkmarx/kics-github-action#96]
When the `output-name` parameter is set to anything other than `"results"` (e.g. using a config file), the action still looks for a file called `results.json`, which then causes an error to be logged in the console

## To reproduce

`kics-config.json`:
```json
{
  "output-name": "my-results"
}
```

Workflow file:
```yml
      - name: "Scan with KICS"
        uses: checkmarx/kics-github-action@v1.7.0
        with:
          path: "."
          config_path: kics-config.json
          platform_type: terraform
          output_path: kics-results
          output_formats: "json,sarif"
```

Error message:
```
Running KICS action...
Error: ENOENT: no such file or directory, open 'kics-results/results.json'
    at Object.openSync (node:fs:603:3)
    at Object.readFileSync (node:fs:471:35)
    at readJSON (/app/dist/index.js:16785:24)
    at main (/app/dist/index.js:16854:31)
    at /app/dist/index.js:16872:1
    at /app/dist/index.js:16874:3
    at Object.<anonymous> (/app/dist/index.js:16877:12)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'kics-results/results.json'
}
```
