### ISSUE TITLE
The argument for -i is not specified

### ISSUE THREAD

**Issue by mos914** [Checkmarx/kics-github-action#98]
# description
- Query ID set in include_query within the with parameter is not being passed as an argument to the command.

# Reproduce
**actions**
``` yaml
  steps:
    - name: kics
      uses: checkmarx/kics-github-action@v1.7.0
      with:
        include_queries: '229588ef-8fde-40c8-8756-f4f2b5825ded'
        path: ./kics
```

# Expected Behavior
- The following command is executed
```
 kics -p ./kics -o ./ --report-formats json          -q /app/bin/assets/queries  --ignore-on-exit results     -i 229588ef-8fde-40c8-8756-f4f2b5825ded
``` 

# Actual Behavior
```
09:11 - INF : about to scan directory ./kics
09:11 - INF : kics command kics -p ./kics -o ./ --report-formats json          -q /app/bin/assets/queries  --ignore-on-exit results     -i    
Error: flag needs an argument: 'i' in -i
```

# Proposed Modification
- Fix the variable definition in entrypoint.sh
https://github.com/Checkmarx/kics-github-action/blob/8a44970e3d2eca668be41abe9d4e06709c3b3609/entrypoint.sh#L31

```bash
[[ ! -z "$INPUT_INCLUDE_QUERIES" ]] && INCLUDE_QUERIES_PARAM="-i $INPUT_INCLUDE_QUERIES" 
```
